"""
Mobitel HR Assistant - Smart Leave Optimizer
Suggests optimal leave dates by combining holidays, weekends, and personal leave
to maximize time off with minimum leave days used.

Features:
- Leave intent detection from natural language queries
- Holiday-aware calendar window finding
- Efficiency-based ranking (best ratio of days off to leave used)
- Month-specific and general suggestions
"""

import re
import json
from datetime import date, timedelta
from typing import Optional, List, Dict, Tuple
from config import setup_logging, BASE_DIR

logger = setup_logging("hr_assistant.leave")

# ============================================================================
# HOLIDAY DATA - Loaded from holidays.json (auto-generated by holiday_parser.py)
# ============================================================================

HOLIDAYS_JSON_PATH = BASE_DIR / "holidays.json"


def load_holidays() -> Tuple[int, list]:
    """
    Load holiday data from holidays.json.
    
    Returns:
        Tuple of (year, list of (date, name) tuples).
        Returns (current_year, []) if file doesn't exist.
    """
    if not HOLIDAYS_JSON_PATH.exists():
        logger.warning(f"holidays.json not found at {HOLIDAYS_JSON_PATH}")
        logger.warning("Run 'python holiday_parser.py' to generate it from the Holiday Planner PDF")
        return date.today().year, []
    
    try:
        with open(HOLIDAYS_JSON_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        year = data.get("year", date.today().year)
        holidays = []
        
        for entry in data.get("holidays", []):
            date_str = entry["date"]
            name = entry["name"]
            parts = date_str.split("-")
            d = date(int(parts[0]), int(parts[1]), int(parts[2]))
            holidays.append((d, name))
        
        logger.info(f"Loaded {len(holidays)} holidays for year {year} from holidays.json")
        return year, holidays
    
    except Exception as e:
        logger.error(f"Error loading holidays.json: {e}")
        return date.today().year, []


# Load holidays at module level
HOLIDAY_PLANNER_YEAR, _HOLIDAY_LIST = load_holidays()
HOLIDAYS = {HOLIDAY_PLANNER_YEAR: _HOLIDAY_LIST}

# Set of holiday dates for fast lookup
HOLIDAY_DATES = {d for d, _ in HOLIDAYS.get(HOLIDAY_PLANNER_YEAR, [])}
HOLIDAY_NAMES = {d: name for d, name in HOLIDAYS.get(HOLIDAY_PLANNER_YEAR, [])}

# Month name mappings
MONTH_NAMES = {
    "january": 1, "jan": 1, "february": 2, "feb": 2, "march": 3, "mar": 3,
    "april": 4, "apr": 4, "may": 5, "june": 6, "jun": 6,
    "july": 7, "jul": 7, "august": 8, "aug": 8, "september": 9, "sep": 9, "sept": 9,
    "october": 10, "oct": 10, "november": 11, "nov": 11, "december": 12, "dec": 12,
}


# ============================================================================
# LEAVE INTENT DETECTION
# ============================================================================

def detect_leave_intent(query: str) -> Optional[Dict]:
    """
    Detect if the user's query is asking for leave/holiday suggestions.
    
    Returns:
        Dict with 'days_wanted' and 'target_month' if leave intent detected,
        None otherwise.
    """
    query_lower = query.lower().strip()
    
    # Keywords that indicate leave suggestion intent
    leave_keywords = [
        "suggest", "recommend", "best day", "best time", "good day", "good time",
        "when should i take", "when to take", "plan leave", "plan my leave",
        "long weekend", "days off", "day off", "leave plan", "leave suggest",
        "holiday plan", "maximize", "optimal leave", "suitable day", "suitable date",
    ]
    
    # Must also have a leave/holiday context word
    context_keywords = [
        "leave", "holiday", "off", "vacation", "break", "rest", "time off",
    ]
    
    has_leave_intent = any(kw in query_lower for kw in leave_keywords)
    has_context = any(kw in query_lower for kw in context_keywords)
    
    if not (has_leave_intent and has_context):
        return None
    
    logger.info("Leave suggestion intent detected")
    
    result = {
        "days_wanted": None,
        "target_month": None,
    }
    
    # Extract number of days wanted
    day_patterns = [
        r'(\d+)\s*(?:day|days)',
        r'(\d+)\s*(?:day|days)\s*(?:leave|off|holiday)',
    ]
    for pattern in day_patterns:
        match = re.search(pattern, query_lower)
        if match:
            result["days_wanted"] = int(match.group(1))
            break
    
    # Check for "long weekend" → 3-4 days
    if result["days_wanted"] is None and "long weekend" in query_lower:
        result["days_wanted"] = 4
    
    # Default to 4 days if no specific number given
    if result["days_wanted"] is None:
        result["days_wanted"] = 4
    
    # Extract target month
    for month_name, month_num in MONTH_NAMES.items():
        if month_name in query_lower:
            result["target_month"] = month_num
            break
    
    # Check for "this month" / "next month"
    today = date.today()
    if "this month" in query_lower:
        result["target_month"] = today.month
    elif "next month" in query_lower:
        next_m = today.month + 1 if today.month < 12 else 1
        result["target_month"] = next_m
    
    logger.info(f"  Days wanted: {result['days_wanted']}, Target month: {result['target_month']}")
    return result


# ============================================================================
# LEAVE WINDOW FINDER
# ============================================================================

def _is_free_day(d: date) -> bool:
    """Check if a date is a weekend or holiday (no personal leave needed)."""
    return d.weekday() >= 5 or d in HOLIDAY_DATES  # 5=Sat, 6=Sun


def _get_day_type(d: date) -> str:
    """Get the type label for a date."""
    if d in HOLIDAY_DATES:
        return f"🎉 {HOLIDAY_NAMES[d]}"
    elif d.weekday() == 5:
        return "🔵 Weekend (Saturday)"
    elif d.weekday() == 6:
        return "🔵 Weekend (Sunday)"
    else:
        return "📝 Personal Leave"


def find_optimal_leave_windows(
    days_wanted: int,
    target_month: Optional[int] = None,
    max_results: int = 3,
) -> List[Dict]:
    """
    Find optimal leave windows that maximize days off with minimum personal leave.
    
    Scans sliding windows across the calendar to find periods where holidays
    and weekends cluster together, minimizing the need for personal leave days.
    
    Args:
        days_wanted: Minimum total consecutive days off desired
        target_month: Optional month to restrict search (1-12)
        max_results: Maximum number of suggestions to return
        
    Returns:
        List of window dicts sorted by efficiency (best first), each containing:
        - start_date, end_date
        - total_days, personal_leave_needed, free_days
        - efficiency (ratio of total_days / personal_leave_needed)
        - day_breakdown: list of (date, type_label) tuples
    """
    year = HOLIDAY_PLANNER_YEAR
    today = date.today()
    
    # Define search range
    if target_month:
        start = date(year, target_month, 1)
        # End of the target month
        if target_month == 12:
            end = date(year, 12, 31)
        else:
            end = date(year, target_month + 1, 1) - timedelta(days=1)
    else:
        # Search the full year but only future dates
        start = max(date(year, 1, 1), today)
        end = date(year, 12, 31)
    
    # Don't suggest past dates unless in target month mode
    if not target_month:
        start = max(start, today)
    
    windows = []
    
    # Try different window sizes (from days_wanted up to days_wanted + 5)
    for window_size in range(days_wanted, days_wanted + 6):
        current = start
        while current + timedelta(days=window_size - 1) <= end:
            window_end = current + timedelta(days=window_size - 1)
            
            # Calculate days breakdown
            breakdown = []
            personal_leave = 0
            free_days = 0
            
            for i in range(window_size):
                d = current + timedelta(days=i)
                day_type = _get_day_type(d)
                breakdown.append((d, day_type))
                
                if _is_free_day(d):
                    free_days += 1
                else:
                    personal_leave += 1
            
            # Only include windows with at least some free days (holidays/weekends)
            # and reasonable personal leave usage
            if free_days > 0 and personal_leave <= days_wanted:
                efficiency = window_size / max(personal_leave, 0.5)  # Higher is better
                
                windows.append({
                    "start_date": current,
                    "end_date": window_end,
                    "total_days": window_size,
                    "personal_leave_needed": personal_leave,
                    "free_days": free_days,
                    "efficiency": efficiency,
                    "day_breakdown": breakdown,
                })
            
            current += timedelta(days=1)
    
    # Sort by: 1) fewest personal leave days, 2) highest total days, 3) earliest
    windows.sort(key=lambda w: (w["personal_leave_needed"], -w["total_days"], w["start_date"]))
    
    # Deduplicate overlapping windows - keep only the best per cluster
    filtered = []
    used_ranges = set()
    for w in windows:
        # Check if this window overlaps significantly with already selected ones
        window_dates = set()
        for i in range(w["total_days"]):
            window_dates.add(w["start_date"] + timedelta(days=i))
        
        overlap = window_dates & used_ranges
        if len(overlap) < len(window_dates) * 0.5:  # Less than 50% overlap
            filtered.append(w)
            used_ranges.update(window_dates)
        
        if len(filtered) >= max_results:
            break
    
    return filtered


# ============================================================================
# RESPONSE FORMATTING
# ============================================================================

def format_leave_suggestion(intent: Dict, windows: List[Dict]) -> str:
    """
    Format leave suggestions into a user-friendly response.
    
    Args:
        intent: The detected intent dict
        windows: List of optimal leave windows
        
    Returns:
        Formatted string response
    """
    if not windows:
        month_text = ""
        if intent.get("target_month"):
            month_names_rev = {v: k.capitalize() for k, v in MONTH_NAMES.items() if len(k) > 3}
            month_text = f" in {month_names_rev.get(intent['target_month'], 'that month')}"
        return (
            f"I couldn't find a good leave window{month_text} with the holidays available. "
            f"Try adjusting the number of days or checking a different month."
        )
    
    days = intent.get("days_wanted", 4)
    lines = [f"Here are the best options to get **{days}+ consecutive days off** using the fewest personal leave days:\n"]
    
    for i, w in enumerate(windows, 1):
        start_str = w["start_date"].strftime("%a, %d %b %Y")
        end_str = w["end_date"].strftime("%a, %d %b %Y")
        
        lines.append(f"**Option {i}: {start_str} → {end_str}**")
        lines.append(f"📅 Total days off: **{w['total_days']}** | "
                     f"Personal leave needed: **{w['personal_leave_needed']}** | "
                     f"Free days: **{w['free_days']}**\n")
        
        for d, dtype in w["day_breakdown"]:
            day_str = d.strftime("%a %d %b")
            lines.append(f"  - {day_str} — {dtype}")
        
        lines.append("")  # blank line between options
    
    lines.append("💡 *Tip: Days marked with 🎉 are company holidays and 🔵 are weekends — no leave needed!*")
    
    return "\n".join(lines)


# ============================================================================
# MAIN ENTRY POINT
# ============================================================================

def handle_leave_query(query: str) -> Optional[str]:
    """
    Main entry point for leave-related queries.
    
    Args:
        query: User's question
        
    Returns:
        Formatted leave suggestion if leave intent detected, None otherwise
    """
    intent = detect_leave_intent(query)
    if intent is None:
        return None
    
    logger.info(f"Processing leave suggestion: {intent}")
    
    windows = find_optimal_leave_windows(
        days_wanted=intent["days_wanted"],
        target_month=intent.get("target_month"),
    )
    
    logger.info(f"Found {len(windows)} optimal leave windows")
    for i, w in enumerate(windows):
        logger.debug(
            f"  Window {i+1}: {w['start_date']} to {w['end_date']} "
            f"({w['total_days']} days, {w['personal_leave_needed']} leave needed)"
        )
    
    return format_leave_suggestion(intent, windows)
